### PR TITLE
use storage container role assignment

### PR DESCRIPTION
**Pull request by kewalaka**
## Purpose

Illustrate a nicer way to do the role assignment, now that this PR is merged

https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/pull/43

## Does this introduce a breaking change?
```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code
*  Run part 5

## What to Check
Verify that the following are valid
* Confirm the role assignment exists on the storage container, and part 6 can be completed.

### CODE REVIEW

**Comment by kewalaka** [comment]
with the release of the storage account AVM module v0.1.1, this now works:

results:

image

& I can complete up to Part 8

image

**Comment by jaredfholgate** [comment]
Hi. I'm unsure about this change since is uses less granular permissions and we loose the AVM role assignments example. I appreciate that is simplifies the code and it would be great if that was the intent of this lab. The intent is to showcase AVM modules though, so although there is extra complexity using the role assignments module, it does show how to implement the granular role assignment using AVM if it is not available on the native AVM as in this case. To be fair we should probably have a method to apply these roles directly in the storage AVM.

**Comment by kewalaka** [comment]
Hi @jaredfholgate I think you're missing the significance of the storage account module change in v0.1.1.

The AVM spec says that child resources must implement role assignments.  The role assignment is at the correct scope (the container) thus is as granular as current state.

I understand this is designed to showcase AVM, but respectfully suggest a better example is needed for role assignments.

Role assignments should use the module interface if it is available, imo.

**Comment by jaredfholgate** [comment]
Hi. Apologies, I missed the fact it was nested under the containers section. I think the doc update threw me off as it was changed from `container` to `account`.

**Comment by kewalaka** [comment]
Another reason for following this pattern is it also translates to other resources, E g. For keyvault children, like secrets or certs, and it aligns to the way roles are done with bicep child resources.

**Review by jaredfholgate — APPROVED** [review]
LGTM

**Pull request merged**
